### ISSUE TITLE
Charging status ''on'' when station is ''plugged_waiting''

### ISSUE THREAD

**Issue by team0220** [Moustachauve/pytechnove#6]
The binary sensor [binary_sensor.famille_b_48_charging] is showing the state ''charging'' while it is in fact ''plugged_waiting'' in [sensor.famille_b_32_status]. 

Maybe the the binary sensor for charging is listening to the state ''plugged'' instead of ''charging'' ?

My setup is one technoVEi48 and one TechnoVEi32 in power sharing mode. In the pictures, both cars are plugged but one is ''plugged_waiting'' and the other is ''plugged_charging''. In both cases, the binary sensor is ''on''.
![Screenshot 2024-02-13 094637](https://github.com/Moustachauve/pytechnove/assets/142860854/3614b1de-58e2-4597-82cf-076ad1de154f)
![Screenshot 2024-02-13 095011](https://github.com/Moustachauve/pytechnove/assets/142860854/cd761728-f850-47fb-809a-d8ae3591e7df)

Au plaisir ! :) and don't hesitate to ask @midiparty or myself if you want to test out some stuff !

**Comment by Moustachauve** [comment]
This sensor uses the direct value from the API "isSessionActive". I marked its device class in Home Assistant as "BinarySensorDeviceClass.BATTERY_CHARGING" which means it gets "charging" when the value is true.

I'm not too sure what that "session active" means in the station. I just did some more experimentation and it seems that this value becomes false when auto-charge is disabled and charging is not allowed.

So I should probably rename that value to more accurately represent what it is actually doing.

**Comment by Moustachauve** [comment]
https://github.com/home-assistant/core/pull/121484 will fix this issue. It replaces the charging status sensor by a new binary sensor called "charging enabled" that also make it possible to start or stop charging.

**Comment by team0220** [comment]
Merci !

S Blanchard

**Comment by team0220** [comment]
Thank you ! Great Job !
